name: Demo Workflow
on: 
  pull_request:
    types: opened #[type1, type2]
    # - opened
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Info
        run: echo "${{toJson(github.event)}}"
      - name: Checkout
        uses: actions/checkout@v6.0.2
      - name: Install Dependencies
        run: npm ci
      - name: Run Tests
        run: npm run test
      - name: Buid
        run: npm run build
      - name: Deploy
        run: echo "Deploying..."